import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateCommand, commandFilename, isGenerated, extractSource } from "../src/convert.mjs";
import { getAgent } from "../src/registry.mjs";

const mockSkill = {
  name: "team-setup",
  description: "Clone, scaffold, or configure a team AI directives repository",
  body: "# Team Setup\n\nThis is the skill body.\n\n## When to Use\n\nWhen you need to set up team directives.",
  dir: "/project/.agents/skills/team-setup",
  frontmatter: { name: "team-setup", description: "Clone, scaffold, or configure a team AI directives repository" },
};

const mockUserInvokedSkill = {
  name: "team-setup",
  description: "Clone, scaffold, or configure a team AI directives repository",
  body: "# Team Setup\n\n## Overview\n\nSet up team directives.\n\n## Core Process\n\nStep 1: Present options.",
  dir: "/project/.agents/skills/team-setup",
  frontmatter: { name: "team-setup", "disable-model-invocation": "true" },
  invocation: "user",
};

const mockModelInvokedSkill = {
  name: "team-boot",
  description: "Bootstrap session",
  body: "# team-boot\n\nBootstrap.",
  dir: "/project/.agents/skills/team-boot",
  frontmatter: { name: "team-boot" },
  invocation: "model",
};

describe("Command generation — Markdown", () => {
  it("generates inline markdown command with frontmatter", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "inline", source: "tikalk/adlc-team-skills" });

    assert.ok(content.startsWith("---\n"));
    assert.ok(content.includes("description: Clone, scaffold, or configure"));
    assert.ok(content.includes("generated by adlc-skills-cli"));
    assert.ok(content.includes("source: tikalk/adlc-team-skills"));
    assert.ok(content.includes("# Team Setup"));
    assert.ok(content.includes("$ARGUMENTS"));
  });

  it("generates wrapper markdown command", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "wrapper", source: "test" });

    assert.ok(content.includes("Invoke the `team-setup` skill."));
    assert.ok(content.includes("$ARGUMENTS"));
    assert.ok(!content.includes("## When to Use"));
  });

  it("includes base directory note in inline mode", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "inline", source: "test" });

    assert.ok(content.includes("Base directory for this skill:"));
    assert.ok(content.includes("/project/.agents/skills/team-setup"));
  });

  it("generates correct filename", () => {
    const agent = getAgent("opencode");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.md");

    const claudeAgent = getAgent("claude-code");
    assert.equal(commandFilename(mockSkill, claudeAgent, {}), "team-setup.md");
  });

  it("applies prefix to filename", () => {
    const agent = getAgent("opencode");
    assert.equal(commandFilename(mockSkill, agent, { prefix: "adlc" }), "adlc.team-setup.md");
  });

  it("generates .prompt.md for copilot", () => {
    const agent = getAgent("github-copilot");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.prompt.md");
  });

  it("generates .mdc for firebender", () => {
    const agent = getAgent("firebender");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.mdc");
  });
});

describe("Command generation — Execution mode (claude-code user-invoked skills)", () => {
  it("user-invoked skill on claude-code gets execution script (model can't invoke user skills)", () => {
    const agent = getAgent("claude-code"); // default_mode: wrapper, no user_invoked_mode → execution
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("<EXTREMELY_IMPORTANT>"), "Execution directive present");
    assert.ok(content.includes("Execute the following workflow"), "Execute instruction present");
    assert.ok(content.includes("## User Input"), "User Input section present");
    assert.ok(content.includes("$ARGUMENTS"), "$ARGUMENTS present");
    assert.ok(content.includes("# Team Setup"), "Full skill body present");
    assert.ok(content.includes("## Core Process"), "Process section preserved");
  });

  it("user-invoked skill on command-only agent stays inline (full body, no directive)", () => {
    const agent = getAgent("amp"); // default_mode: inline
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("# Team Setup"), "Full body inlined");
    assert.ok(!content.includes("<EXTREMELY_IMPORTANT>"), "No execution directive for command-only (uses plain inline)");
  });
});

describe("Command generation — TOML", () => {
  it("generates TOML for gemini-cli", () => {
    const agent = getAgent("gemini-cli");
    const content = generateCommand(mockSkill, agent, { source: "test" });

    assert.ok(content.includes('description ='));
    assert.ok(content.includes('prompt = """'));
    assert.ok(content.includes("# generated by adlc-skills-cli"));
    assert.ok(content.includes("{{args}}"));
  });

  it("generates .toml filename", () => {
    const agent = getAgent("gemini-cli");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.toml");
  });
});

describe("Command generation — YAML", () => {
  it("generates YAML for goose", () => {
    const agent = getAgent("goose");
    const content = generateCommand(mockSkill, agent, { source: "test" });

    assert.ok(content.includes("description:"));
    assert.ok(content.includes("prompt: |"));
    assert.ok(content.includes("# generated by adlc-skills-cli"));
    assert.ok(content.includes("{{args}}"));
  });

  it("generates .yaml filename", () => {
    const agent = getAgent("goose");
    assert.equal(commandFilename(mockSkill, agent, {}), "team-setup.yaml");
  });
});

describe("Generated file detection", () => {
  it("isGenerated detects our header", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { source: "tikalk/adlc-team-skills" });
    assert.ok(isGenerated(content));
  });

  it("isGenerated returns false for user-created files", () => {
    assert.ok(!isGenerated("# My custom command\n\nDo something."));
  });

  it("extractSource returns the source origin", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { source: "tikalk/adlc-team-skills" });
    assert.equal(extractSource(content), "tikalk/adlc-team-skills");
  });
});

describe("Command generation — opencode user-invoked skills (wrapper)", () => {
  it("opencode user-invoked skill gets wrapper (skill is in available_skills)", () => {
    const agent = getAgent("opencode"); // user_invoked_mode: "wrapper"
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("Invoke the `team-setup` skill."), "Wrapper directive present");
    assert.ok(!content.includes("<EXTREMELY_IMPORTANT>"), "No execution/invoke directive");
    assert.ok(!content.includes("## Core Process"), "Full skill body NOT inlined");
    assert.ok(content.includes("$ARGUMENTS"), "$ARGUMENTS present");
  });

  it("claude-code user-invoked skill gets execution (model can't invoke user skills)", () => {
    const agent = getAgent("claude-code"); // no user_invoked_mode → execution
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("<EXTREMELY_IMPORTANT>"), "Execution directive present");
    assert.ok(content.includes("# Team Setup"), "Full skill body inlined");
    assert.ok(!content.includes("Invoke the `team-setup` skill."), "No wrapper for claude-code user-invoked");
  });

  it("model-invoked skill on opencode stays wrapper", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockModelInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("Invoke the `team-boot` skill."), "Wrapper directive present");
    assert.ok(!content.includes("<EXTREMELY_IMPORTANT>"), "No execution directive for model-invoked");
  });

  it("explicit mode override takes precedence over user_invoked_mode", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockUserInvokedSkill, agent, { mode: "execution", source: "test" });

    assert.ok(content.includes("<EXTREMELY_IMPORTANT>"), "Execution override respected");
    assert.ok(content.includes("# Team Setup"), "Full body inlined when execution forced");
  });
});

describe("Command generation — User Input framing (args forwarding)", () => {
  it("wrapper mode frames $ARGUMENTS under ## User Input with consume-direct directive", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("## User Input"), "User Input heading present in wrapper body");
    assert.ok(content.includes("$ARGUMENTS"), "Args placeholder present");
    assert.ok(
      content.includes("do not ask the user to repeat or rephrase"),
      "Consume-direct directive present",
    );
    assert.ok(
      content.includes("If this section is empty, proceed with the skill's default first step"),
      "Empty-case fallback present",
    );
  });

  it("wrapper does not double-append $ARGUMENTS (placeholder owned by body)", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });
    const occurrences = (content.match(/\$ARGUMENTS/g) || []).length;
    assert.equal(occurrences, 1, "$ARGUMENTS appears exactly once (no duplicate append)");
  });

  it("execution mode frames $ARGUMENTS under ## User Input with same directive", () => {
    const agent = getAgent("claude-code");
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });

    assert.ok(content.includes("## User Input"), "User Input heading present in execution body");
    assert.ok(content.includes("$ARGUMENTS"), "Args placeholder present");
    assert.ok(
      content.includes("do not ask the user to repeat or rephrase"),
      "Consume-direct directive present in execution body",
    );
  });

  it("execution does not double-append $ARGUMENTS", () => {
    const agent = getAgent("claude-code");
    const content = generateCommand(mockUserInvokedSkill, agent, { source: "test" });
    const occurrences = (content.match(/\$ARGUMENTS/g) || []).length;
    assert.equal(occurrences, 1, "$ARGUMENTS appears exactly once in execution body");
  });

  it("wrapper on TOML agent uses {{args}} placeholder in User Input block", () => {
    const geminiAgent = getAgent("gemini-cli");
    const opencodeWithTomlPlaceholder = { ...getAgent("opencode"), args_placeholder: "{{args}}" };
    const content = generateCommand(mockUserInvokedSkill, opencodeWithTomlPlaceholder, {
      mode: "wrapper",
      source: "test",
    });

    assert.ok(content.includes("## User Input"), "User Input heading present");
    assert.ok(content.includes("{{args}}"), "TOML placeholder used in wrapper body");
    assert.ok(!content.includes("$ARGUMENTS"), "No markdown placeholder leaked into TOML agent");
  });

  it("wrapper on YAML agent uses {{args}} placeholder in User Input block", () => {
    const yamlWrapperAgent = { ...getAgent("goose"), default_mode: "wrapper", user_invoked_mode: "wrapper" };
    const content = generateCommand(mockUserInvokedSkill, yamlWrapperAgent, {
      mode: "wrapper",
      source: "test",
    });

    assert.ok(content.includes("## User Input"), "User Input heading present in YAML");
    assert.ok(content.includes("{{args}}"), "YAML placeholder used in wrapper body");
    assert.ok(
      (content.match(/\{\{args\}\}/g) || []).length === 1,
      "{{args}} appears exactly once in YAML wrapper (no double-append)",
    );
  });

  it("inline mode is unaffected — appends $ARGUMENTS externally, no User Input block", () => {
    const agent = getAgent("opencode");
    const content = generateCommand(mockSkill, agent, { mode: "inline", source: "test" });

    assert.ok(content.includes("$ARGUMENTS"), "Inline still appends placeholder");
    assert.ok(!content.includes("## User Input"), "Inline does not add User Input framing");
  });
});
